# Generated by Django 3.2.2 on 2021-05-28 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('FirstName', models.CharField(max_length=30, null=True)),
                ('LastName', models.CharField(max_length=30, null=True)),
                ('Address', models.CharField(max_length=30, null=True)),
                ('City', models.CharField(max_length=30, null=True)),
                ('Country', models.CharField(max_length=30, null=True)),
                ('DOB', models.DateField(default=None, null=True)),
                ('PostalCode', models.IntegerField(null=True)),
                ('sex', models.CharField(max_length=6, null=True)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_loggedin', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=profiles.models.get_default_profile_image, max_length=255, null=True, upload_to=profiles.models.get_profile_image_filepath)),
                ('hide_email', models.BooleanField(default=True)),
                ('about_me', models.TextField(default='test')),
            ],
        ),
        migrations.CreateModel(
            name='Questiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_one', models.CharField(max_length=30)),
                ('option_two', models.CharField(max_length=30)),
                ('option_three', models.CharField(max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='questionnaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question1', models.CharField(max_length=30, null=True)),
                ('question2', models.CharField(max_length=30, null=True)),
                ('question3', models.CharField(max_length=30, null=True)),
                ('question4', models.CharField(max_length=30, null=True)),
                ('question5', models.CharField(max_length=30, null=True)),
                ('question6', models.CharField(max_length=30, null=True)),
                ('question7', models.CharField(max_length=30, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
